// <auto-generated />
using System;
using ChoreographySaga.OrdersService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChoreographySaga.OrdersService.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20240623134945_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChoreographySaga.OrdersService.Persistence.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderUuid");

                    b.HasIndex("OrderUuid")
                        .IsUnique();

                    b.ToTable("Order", "orders");
                });

            modelBuilder.Entity("ChoreographySaga.OrdersService.Persistence.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderProductUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderUuid")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductUuid")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderProductUuid");

                    b.HasIndex("OrderProductUuid")
                        .IsUnique();

                    b.HasIndex("OrderUuid");

                    b.ToTable("OrderProduct", "orders");
                });

            modelBuilder.Entity("ChoreographySaga.OrdersService.Persistence.Entities.OrderProduct", b =>
                {
                    b.HasOne("ChoreographySaga.OrdersService.Persistence.Entities.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderUuid");
                });

            modelBuilder.Entity("ChoreographySaga.OrdersService.Persistence.Entities.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
